### ISSUE TITLE
Public Facing Roadmap

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#115]
- [ ] Develop image/visual of roadmap at high level (Amber)

- [ ] Integrate with Github so issues show up on roadmap to our MDC website (Kristian)

- [ ] Make postcards with visual

**Comment by kjgarza** [comment]
- [ ]  do this
